### ISSUE TITLE
support token-based upload to PyPI

### ISSUE THREAD

**Issue by brainwane** [pypa/flit#276]
Hi! PyPI's getting ready to add upload tokens to its API, so packagers can upload using tokens instead of username/password.

I thought you might want to test and verify that flit's upload works with this. Instructions for testing the pull request: https://github.com/pypa/warehouse/issues/994#issuecomment-512634222

It would be great if you could leave a comment on https://github.com/pypa/warehouse/pull/6084 telling us whether it works for you! This will help us avoid headaches when we roll out the feature on pypi.org.

**Comment by takluyver** [comment]
Thanks. I'm just about to go offline for a week, and then it will be another few days while I dig myself out from the emails that build up. But I'll try to get round to it.

**Comment by brainwane** [comment]
Please do enjoy your offline time! And if someone else would like to do the testing -- maybe @flying-sheep? -- that would, of course, be fine!

**Comment by brainwane** [comment]
This beta feature is now live on PyPI and Test PyPI: https://pypi.org/help/#apitoken

**Comment by Carreau** [comment]
Tried it; worg great. Just set `FLIT_USERNAME='@token'` and `FLIT_PASSWORD='<yourtoken>'`. 

One question we may want to adress is how we pick [which token for which project](https://github.com/pypa/packaging.python.org/issues/628) if not in an env variable.

**Comment by takluyver** [comment]
Brainstorming how the UI could work:

If I'm trying to publish a release of `austin` and my `~/.pypirc` says:

```ini
[pypi]
repository: https://upload.pypi.org/legacy/
username: takowl
```

Then flit could use the first it finds of:

```python
# Project scoped token
keyring.get_password("https://upload.pypi.org/legacy/", "pypi-project-token:austin")

# User scoped token
keyring.get_password("https://upload.pypi.org/legacy/", "pypi-user-token:takowl")
```

If it doesn't find either of those, it would ideally connect as my user, prompting me for any necessary credentials, and then obtain and save a project-scoped token to use for uploads. If that's not possible, it might fall back to uploading with username & password as it currently does.

Does that scheme fit in with how you'd like to use tokens? Of course, it could all be overridden by env variables for CI - I'm just thinking about the upload-from-local case.

**Comment by brainwane** [comment]
cc @di and @ewdurbin and @dstufft to answer this question. @woodruffw as an FYI.

**Comment by Carreau** [comment]
The idea would work with me I had something similar in mind wihtout exact details; I'd just like the inerface to be (more or less) standardized across tools that can publish packages. That give us a chance to – at some point  – have a tools to list and manipulate tokens. 

Thus I could not trust flit ; and do somehting like `pip add-token austin <token>`, and flit would be able to pick it up.

**Comment by takluyver** [comment]
It would certainly be good if we could ensure different tools can use the same credentials. I think flit and twine can currently use the same usernames & passwords in keyring, since there's one obvious way to store that. It might take a bit more coordination for tokens. Or maybe flit can just use twine.

**Comment by brainwane** [comment]
Hi - this feature is now out of beta, so I hope you can officially support it!

**Comment by brainwane** [comment]
Changed the title to reflect that this is now a feature and documentation request.

**Comment by kown7** [comment]
> 
> 
> Tried it; worg great. Just set `FLIT_USERNAME='@token'` and `FLIT_PASSWORD='<yourtoken>'`.

I had to use `FLIT_USERNAME=__token__`

**Comment by woodruffw** [comment]
> > 
> 
> I had to use `FLIT_USERNAME=__token__`

Yep, this makes sense: the `@token` name was removed before the beta ended.

**Comment by kown7** [comment]
Is there some documentation planned for this?

**Comment by ewdurbin** [comment]
This is currently documented at https://packaging.python.org/specifications/pypirc/?highlight=token#using-a-pypi-token and https://pypi.org/help/#apitoken

**Comment by chrisjsewell** [comment]
FYI, I do this in a Github action (triggered by a tagged release), so you can then keep the token in a repository secret:

```yaml
  publish:
    name: Publish to PyPi
    needs: [pre-commit, tests]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install flit
      run: |
        pip install flit~=3.0
    - name: Build and publish
      run: |
        flit publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
```

see for example: https://github.com/executablebooks/mdformat-tables/blob/a83ba37580c8f6c1827bce59a285ea62f47f56d5/.github/workflows/tests.yml#L74
