### ISSUE TITLE
Does pip ships flit_core internally?

### ISSUE THREAD

**Issue by kbumsik-angelswing** [pypa/flit#486]
I am trying to make a new python project using PEP 621.

I firstly updated pip using `python -m pip install --upgrade pip`.

So pip version is the following:

```
python -m pip  --version 
pip 21.3.1 from /Users/kbumsik/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip (python 3.10)
```

My `pyproject.toml` was like this:
```toml
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
...
...
```

Then running `pip install -e .` or `pip install .` works, successfully installs dependencies.

But the point is, **I even didn't install `flit` yet**, I mean, I didn't `python -m pip install flit` yet and I can't import flit_core in the Python shell.

Does the latest `pip` ships flit_core internally?

Thank you.
