### ISSUE TITLE
Inconsistency in `_` -> `-` normalization

### ISSUE THREAD

**Issue by Conchylicultor** [pypa/flit#503]
I'm using a PEP 621 toml using flit 3.5 & pip 21.3.1:

My toml has self-refering `optional-dependencies`:

```toml
[build-system]
requires = ["flit_core >=3.5,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "etils"

[project.optional-dependencies]
array_types = ["numpy"]
all = ["etils[array_types]"]
```

When running `pip install -e .[all]`, this logs:

```
WARNING: etils 0.2.0 does not provide the extra 'array-types'
```

It looks like `"etils[array_types]"` gets normalized to `[array-types]`, but not `array_types = ["numpy"]`.

Manually replacing `array_types = ["numpy"]` -> `array-types = ["numpy"]` solve the issue.

But this behavior feels inconsistent.

**Comment by takluyver** [comment]
[PEP 508](https://www.python.org/dev/peps/pep-0508/), which defines the syntax for specifying extras, allows `-_.` in the name of an extra, and doesn't specify any normalisation rule, which suggests that `array_types` and `array-types` are two separate extras. I'd guess that pip normalises them, probably like distribution names ([rule in PEP 503](https://www.python.org/dev/peps/pep-0503/#normalized-names)). I don't know if there's any other spec that says this is the right thing to do, or if it's just following something that setuptools/easy_install have done without it ever being written in any spec.

The [core metadata spec says](https://packaging.python.org/en/latest/specifications/core-metadata/#provides-extra-multiple-use) that an extra name "must be a valid Python identifier", which implies that `array-types` is not even a legal value. That conflicts with PEP 508, so at least one of the specs must be wrong. :shrug:

**Comment by pradyunsg** [comment]
Here's what flit generates:

```yaml
Requires-Dist: installer[array_types] ; extra == "all"
Requires-Dist: numpy ; extra == "array_types"
Provides-Extra: all
Provides-Extra: array_types
```

This is definitely a pip bug.
