### ISSUE TITLE
flit doesn't follow symlinks when pulling in `include = ` in pyproject.toml

### ISSUE THREAD

**Issue by Torxed** [pypa/flit#509]
Using a `pyproject.toml` which includes:
```toml
[tool.flit.sdist]
include = ["docs/","profiles"]
exclude = ["docs/*.html", "docs/_static","docs/*.png","docs/*.psd"]
```

There will be no `<module path>/profiles/` included if the inclusion is a symlink.
The following issue can be observed here: https://github.com/archlinux/archinstall/tree/master/archinstall
Where `profiles/` and `examples/` is a symlink to the root of the project to make it easier to find and manage examples and profiles.

This used to work with `setup.py` and the old ways of `pip` `include_data` *(I believe it was)*.
Workaround and discussion can be found here: https://github.com/archlinux/archinstall/issues/832

Is there any reason why symlinks are not followed? It would be a convenient way to source outside data when needed.
Perhaps it is supported but finding the information is hard in that case, been looking around on https://flit.readthedocs.io/en/latest/index.html but there's no mentions of symlinks. Except for `--symlink` of course.
