### ISSUE TITLE
A way to build a package with custom namespace/import name

### ISSUE THREAD

**Issue by dinhanhx** [pypa/flit#598]
Assuming the following structure
```
project_name/
├── src/
│   ├── __init__.py
│   ├── foo.py
│   └── bar.py
└── drive.py
```
with [setuptools](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html), I can do the following in `pyproject.toml`, 
```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dummy"
version = "0.0.1"

[tool.setuptools]
package-dir = {"dummy" = "src"}

```
The cmd `python -m build` will build the src folder into a package called `dummy` ([Relevant SO question](https://stackoverflow.com/questions/14417236/setup-py-renaming-src-package-to-project-name)). I wonder whether flit can do such that?

However, I'm aware of [module section](https://flit.pypa.io/en/latest/pyproject_toml.html#module-section) of flit. From my understanding, this allows you to have different name on pypi and import name but no way to specify `src/` is *that* import name.
