### ISSUE TITLE
Wrong/misleading metadata if multiple maintainers are set

### ISSUE THREAD

**Issue by stefan6419846** [pypa/flit#720]
At *pypdf*, we recently added a second maintainer:

```toml
[project]
name = "pypdf"
authors = [{ name = "Mathieu Fenniak", email = "biziqe@mathieu.fenniak.net" }]
maintainers = [{ name = "stefan6419846" }, { name = "Martin Thoma", email = "info@martin-thoma.de" }]
```

This leads to some strange/misleading metadata files:

```
Metadata-Version: 2.3
Name: pypdf
Version: 5.3.0
Summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
Author-email: Mathieu Fenniak <biziqe@mathieu.fenniak.net>
Maintainer: stefan6419846
Maintainer-email: Martin Thoma <info@martin-thoma.de>
```

I would have expected something like this:

```
Metadata-Version: 2.3
Name: pypdf
Version: 5.3.0
Summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
Author-email: Mathieu Fenniak <biziqe@mathieu.fenniak.net>
Maintainer: stefan6419846, Martin Thoma
Maintainer-email: info@martin-thoma.de
```
